### ISSUE TITLE
More comment plz

### ISSUE THREAD

**Issue by otajor** [tasminions/failures-and-champs#21]
E.g. https://github.com/tasminions/failures-and-champs/blob/master/lib/controllers/leaderboard.js#L39-L59

You skip from step 2 to step 6... would be good to have some kind of explanation of what's going on in between : )

**Comment by andrewMacmurray** [comment]
I have to agree with this, I think it's brilliant you're using bluebird but because a lot of us don't know what it is or how it works (and even how promises work), and because the purpose of these projects is for all of us to learn I think comments on what each bit is doing (particularly the bluebird methods) would be really valuable for all of us.

Great work! :heart: :sparkles: :+1:

**Comment by eliasmalik** [comment]
Yup, did have comments of each step before we switched to bluebird, but they got lost in the re-write. Will re-add

**Comment by otajor** [comment]
Cheers, this is easier to follow :+1: 

Closing issue.
